repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: "trailing-whitespace"
      - id: "debug-statements"
      - id: "end-of-file-fixer"
      - id: "check-toml"
      - id: "check-yaml"
