version: "3.9"

name: "like_poker"

services:
  web:
    image: nginx:latest
    command: /bin/sh -c \
      "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && \
      nginx -g 'daemon off;'"
    depends_on:
      - auth
      - balance
      - collection
      - file
      - like
    env_file:
      - ${PWD}/.env
    ports:
      - ${PORT}:${PORT}
    networks:
      - like_network
    volumes:
      - ${PWD}/nginx:/etc/nginx

networks:
  like_network:
    name: "like_network"
