version: "3.9"

name: "likepoker"

services:
  web:
    image: fabiocicerchia/nginx-lua:latest
    command: /bin/sh -c \
      "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && \
      nginx -g 'daemon off;'"
    depends_on:
      - auth_backend
      - balance_backend
      - collection_backend
      - file_backend
    env_file:
      - ${PWD}/.env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
